---
socket_address: 127.0.0.1:5000
error_verbosity: Full
api_key_header_name: x-api-key
api_keys:
  - api-key-1
  - api-key-2
basic_auth_users:
  - username: admin
    password: admin
openid_configuration_url: https://keycloak.com/realms/master/.well-known/openid-configuration
jwks_time_to_live_in_seconds: 300
audience: 
  - account